
-- =============================================
--
-- Author:		
-- Create date: 2016-06-05
-- Description:	
--		Return all Foreign Key columns for Dimension and Fact tables.
--		Used by DW BIML-script to setup flows to handle Inferred members
-- Example:	
--
--
-- =============================================
CREATE VIEW [ssis].[DimensionForeignKeyColumns]
AS
/*
		Return all Foreign Key columns for Dimension and Fact tables.
		Used by DW BIML-script to setup flows to handle Inferred members
	*/
SELECT SrcDim.DimensionTableCatalog
	, SrcDim.DimensionSchemaName
	, SrcDim.DimensionTableName
	, FkDim.ForeignKeyTableName
	, SrcDim.ForeignKeyColumn
	, FkDim.ForeignKeyColumn as ForeignKeyTableColumnName

FROM (
	-- Dimension and Foreign Key data
	SELECT dt.DestinationTableCatalog DimensionTableCatalog
		,dt.DestinationSchemaName DimensionSchemaName
		,dt.DestinationTableName DimensionTableName
		,COLUMN_NAME AS ForeignKeyColumn
	FROM Metadata.SourceField sf
	JOIN Metadata.DestinationTable dt ON sf.TABLE_CATALOG = dt.SourceTableCatalog
		AND sf.TABLE_SCHEMA = dt.SourceSchemaName
		AND sf.TABLE_NAME = dt.SourceTableName
	WHERE dt.DestinationTableCatalog = (SELECT TOP 1 [NormEnvironmentName]
										FROM [Metadata].[EnvironmentVariables])
		AND dt.GroupName IN (
			'Dimension'
			,'Fact'
			)
		AND COLUMN_NAME LIKE '%_bkey'
		AND replace(column_name, '_bkey', '') != STUFF(dt.DestinationTableName, 1, 2, '')
		-- exclude Key columns generated by DestinationFieldExtended  
		AND NOT EXISTS (
			SELECT 1
			FROM Metadata.DestinationFieldExtended x
			WHERE x.COLUMN_NAME = sf.COLUMN_NAME
				AND x.DestinationTableCatalog = dt.DestinationTableCatalog
				AND x.COLUMN_NAME LIKE '%_bkey'
			)
	) SrcDim
JOIN (
	-- Foreign Key Table and Column Data
	SELECT tkd.TableCatalog ForeignKeyTableCatalog
		,tkd.SchemaName ForeignKeyTableSchemaName
		,tkd.TableName ForeignKeyTableName
		,COLUMN_NAME ForeignKeyColumn
	FROM Metadata.TableKeyDefinition tkd
	WHERE COLUMN_NAME LIKE '%_bkey'
		AND replace(column_name, '_bkey', '') = STUFF(TableName, 1, 2, '')
		AND TableCatalog = (SELECT TOP 1 [NormEnvironmentName]
							FROM [Metadata].[EnvironmentVariables])
		AND KeyType = 'PK'
	) FkDim ON SrcDim.DimensionTableCatalog = FkDim.ForeignKeyTableCatalog
	AND SrcDim.DimensionSchemaName = FkDim.ForeignKeyTableSchemaName
	AND (SrcDim.ForeignKeyColumn = FkDim.ForeignKeyColumn 
			or left(SrcDim.ForeignKeyColumn, CHARINDEX('_', SrcDim.ForeignKeyColumn, 1)-1) + '_bkey' = FkDim.ForeignKeyColumn
		)

	AND fkDim.ForeignKeyColumn != 'SourceSystemKey'