/*
Deployment script for DWH_6_DataAccess

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DWH_3_Fact "DWH_3_Fact"
:setvar DatabaseName "DWH_6_DataAccess"
:setvar DefaultFilePrefix "DWH_6_DataAccess"
:setvar DefaultDataPath "E:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "E:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering [CityNetwork].[f_Penetration]...';


GO



ALTER VIEW [CityNetwork].[f_Penetration]
AS
SELECT Date = CAST(CAST(fp.Calendar_key AS NVARCHAR(8)) AS DATE)
     , fp.Opportunity_key
	 , do.CustomerCategory_key	 
     , fp.Area_key
     , fp.Project_key
     , fp.SalesOrder_key
     , fp.Customer_key
     , fp.Access_key
     , fp.NoOfHP
     , fp.NoOfHC
     , fp.NoOfInstalled 
	 , Scenario_bkey = LEFT(CAST(fp.Calendar_key AS NVARCHAR(8)), 4) + 'A'
	 , PlanningAmount = 0
	 , Phase_bkey = 'N/A'
FROM [$(DWH_3_Fact)].Fact.f_Penetration fp
INNER JOIN [$(DWH_3_Fact)].Fact.d_Opportunity do ON do.Opportunity_key = fp.Opportunity_key 
WHERE fp.SysDatetimeDeletedUTC IS NULL
UNION ALL 
SELECT Date = CAST(CAST(fp.Calendar_key AS NVARCHAR(8)) AS DATE)
     , Opportunity_key		   = -1
	 , fp.CustomerCategory_key	   
     , Area_key				   = -1
     , Project_key			   = -1
     , SalesOrder_key		   = -1
     , Customer_key			   = -1
     , Access_key			   = -1
     , NoOfHP				   = -1
     , NoOfHC				   = -1
     , NoOfInstalled 		   = -1
	 , fp.Scenario_bkey
	 , PlanningAmount		   =  fp.Amount
	 , fp.Phase_bkey 
FROM [$(DWH_3_Fact)].Fact.f_Planning fp
GO
PRINT N'Update complete.';


GO
