/*
Deployment script for DWH_6_DataAccess

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DWH_3_Fact "DWH_3_Fact"
:setvar DatabaseName "DWH_6_DataAccess"
:setvar DefaultFilePrefix "DWH_6_DataAccess"
:setvar DefaultDataPath "E:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "E:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering [CityNetwork].[d_Area]...';


GO
ALTER VIEW CityNetwork.d_Area
AS
SELECT		da.Area_key
			, da.Geography_key
			, da.Area_bkey
			, da.AreaName
			, MetroNetworkManager = Employee_MetroNetworkManager_key.FieldValue
			, RegionConstructionManager = Employee_RegionConstructionManager_key.FieldValue
			, DeliveryStreamLeader = Employee_DeliveryStreamLeader_key.FieldValue
			, ConstructionManager = Employee_ConstructionManager_key.FieldValue
			, ConstructionStatus = SugarEnum_ConstructionStatus_key.FieldValue
			, SalesStatus = SugarEnum_SalesStatus_key.FieldValue
			, SourcingStatus = SugarEnum_SourcingStatus_key.FieldValue
			, IikStatus = SugarEnum_IikStatus_key.FieldValue
			, AreaType = SugarEnum_AreaType_key.FieldValue
			, Contractor = SugarEnum_Contractor_key.FieldValue
			, SalesOrganisation = SugarEnum_SalesOrganisation_key.FieldValue
			, ConstructionOrganisation = SugarEnum_ConstructionOrganisation_key.FieldValue
			, SubsidyArea = SugarEnum_SubsidyArea_key.FieldValue
			, ProjectDesign = SugarEnum_ProjectDesign_key.FieldValue
			, CountyAdvisoryBoardStatus = SugarEnum_CountyAdvisoryBoardStatus_key.FieldValue
			, da.InitialSalesStart
			, da.AfterMarketSalesStart
			, da.StrategicNetworkPlanningComplete
			, da.LeasedUplinkExpected
			, da.LeasedUplinkDeployed
			, da.TRVPermissionNeeded
			, da.SumOfTRVNeeded
			, da.SumOfTRVSubmitted
			, da.SumOfTRVApproved
			, da.ExpectedApprovalOfTRV
			, da.AllTRVApplicationsSubmitted
			, da.AllTRVApplicationsApproved
			, da.CommentOnTRV
			, da.MunicipalLandPermit
			, da.BuildingPermitApproved
			, da.AllBuildingPermitsSubmitted
			, da.CommentOnBuildingPermit
			, da.PlannedInstallationStart
			, da.PlannedInstallationComplete
			, da.PlannedConstructionStart
			, da.FinalDocumentationComplete
FROM		[$(DWH_3_Fact)].Fact.d_Area da
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum Employee_MetroNetworkManager_key
			ON Employee_MetroNetworkManager_key.SugarEnum_key			= da.Employee_MetroNetworkManager_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum Employee_RegionConstructionManager_key
			ON Employee_RegionConstructionManager_key.SugarEnum_key		= da.Employee_RegionConstructionManager_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum Employee_DeliveryStreamLeader_key
			ON Employee_DeliveryStreamLeader_key.SugarEnum_key			= da.Employee_DeliveryStreamLeader_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum Employee_ConstructionManager_key
			ON Employee_ConstructionManager_key.SugarEnum_key			= da.Employee_DeliveryStreamLeader_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum SugarEnum_ConstructionStatus_key
			ON SugarEnum_ConstructionStatus_key.SugarEnum_key			= da.SugarEnum_ConstructionStatus_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum SugarEnum_SalesStatus_key
			ON SugarEnum_SalesStatus_key.SugarEnum_key					= da.SugarEnum_SalesStatus_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum SugarEnum_SourcingStatus_key
			ON SugarEnum_SourcingStatus_key.SugarEnum_key				= da.SugarEnum_SourcingStatus_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum SugarEnum_IikStatus_key
			ON SugarEnum_IikStatus_key.SugarEnum_key					= da.SugarEnum_IikStatus_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum SugarEnum_AreaType_key
			ON SugarEnum_AreaType_key.SugarEnum_key						= da.SugarEnum_AreaType_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum SugarEnum_Contractor_key
			ON SugarEnum_Contractor_key.SugarEnum_key					= da.SugarEnum_Contractor_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum SugarEnum_SalesOrganisation_key
			ON SugarEnum_SalesOrganisation_key.SugarEnum_key			= da.SugarEnum_SalesOrganisation_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum SugarEnum_ConstructionOrganisation_key
			ON SugarEnum_ConstructionOrganisation_key.SugarEnum_key		= da.SugarEnum_ConstructionOrganisation_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum SugarEnum_SubsidyArea_key
			ON SugarEnum_SubsidyArea_key.SugarEnum_key					= da.SugarEnum_SubsidyArea_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum SugarEnum_ProjectDesign_key
			ON SugarEnum_ProjectDesign_key.SugarEnum_key				= da.SugarEnum_ProjectDesign_key
INNER JOIN	[$(DWH_3_Fact)].Fact.d_SugarEnum SugarEnum_CountyAdvisoryBoardStatus_key
			ON SugarEnum_CountyAdvisoryBoardStatus_key.SugarEnum_key	= da.SugarEnum_CountyAdvisoryBoardStatus_key
GO
PRINT N'Altering [CityNetwork].[d_CustomerCategory]...';


GO
ALTER VIEW CityNetwork.d_CustomerCategory
AS

SELECT  dcc.CustomerCategory_key	
		 , dcc.CustomerCategory
		 , dcc.SalesHierarchy
FROM [$(DWH_3_Fact)].Fact.d_CustomerCategory dcc
GO
PRINT N'Altering [CityNetwork].[f_Penetration]...';


GO

ALTER VIEW [CityNetwork].[f_Penetration]
AS
SELECT Date = CAST(CAST(fp.Calendar_key AS NVARCHAR(8)) AS DATE)
     , fp.Opportunity_key
     , fp.Area_key
     , fp.Project_key
     , fp.SalesOrder_key
     , fp.Customer_key
     , fp.Access_key
     , fp.NoOfHP
     , fp.NoOfHC
     , fp.NoOfInstalled 
FROM [$(DWH_3_Fact)].Fact.f_Penetration fp
WHERE fp.SysDatetimeDeletedUTC IS NULL
GO
PRINT N'Altering [CityNetwork].[f_Subscription]...';


GO
ALTER VIEW CityNetwork.f_Subscription
AS

SELECT  fs.Subscription_key
      , fs.SubscriptionProduct_key
      , fs.Access_key
      , fs.ServiceProvider_key
      , Calendar_key = CAST(CAST(fs.Calendar_key AS NVARCHAR(8)) AS DATE)
	  , Customer_key = ISNULL(t.Customer_key, -1)
      , CustomerType = IIF(t.Customer_key IS NULL, 'MDU', 'SDU')
	  , fs.NoOfActivation          	  
FROM    [$(DWH_3_Fact)].Fact.f_Subscription fs
LEFT JOIN (SELECT do.Access_key, dso.SalesOrder_key AS Customer_key FROM [$(DWH_3_Fact)].Fact.d_Opportunity do INNER JOIN [$(DWH_3_Fact)].Fact.d_SalesOrder dso ON dso.Opportunity_key = do.Opportunity_key WHERE do.Access_key <> -1) t
	ON t.Access_key = fs.Access_key
WHERE fs.SysDatetimeDeletedUTC IS NULL
GO
PRINT N'Creating [CityNetwork].[f_Planning]...';


GO
CREATE VIEW CityNetwork.f_Planning
AS

SELECT  Date = CAST(CAST(fp.Calendar_key AS NVARCHAR(8)) AS DATE)
		 , fp.CustomerCategory_key
		 , fp.Scenario_bkey
		 , fp.Phase_bkey		 
		 , fp.Amount 
FROM [$(DWH_3_Fact)].Fact.f_Planning fp
WHERE fp.SysDatetimeDeletedUTC IS NULL
GO
PRINT N'Update complete.';


GO
