/*
Deployment script for DWH_0_Admin

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DropboxPath "C:\Users\pedram.birounvand\Dropbox (EQT AB)\DataWarehouse\DEV"
:setvar Environment "Local"
:setvar DatabaseName "DWH_0_Admin"
:setvar DefaultFilePrefix "DWH_0_Admin"
:setvar DefaultDataPath "E:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "E:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
-- Test

IF 'Local' = '$(Environment)'
BEGIN
PRINT '***** Creating Test Data for UTV Enviroment *****';


/*
SELECT 'UNION SELECT '
	  ,'''' + [ConfigurationFilter]+ ''','
      ,'''' + [ConfiguredValue]+ ''','
      ,'''' + [PackagePath]+ ''','
      ,'''' + [ConfiguredValueType]+ ''''
  FROM [dbo].[SSISConfigurations]
*/


TRUNCATE TABLE dbo.SSISConfigurations

INSERT INTO dbo.SSISConfigurations(ConfigurationFilter, ConfiguredValue, PackagePath, ConfiguredValueType)
SELECT 	'DWH_3_Fact',	'Data Source=Localhost;Initial Catalog=DWH_3_Fact;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_3_Fact].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_2_Norm',	'Data Source=Localhost;Initial Catalog=DWH_2_Norm;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_2_Norm].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_1_Raw',	'Data Source=Localhost;Initial Catalog=DWH_1_Raw;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_1_Raw].Properties[ConnectionString]',	'String'
UNION SELECT 	'SSAS_Server',	'Data Source=localhost;PROVIDER=MSOLAP;Impersonation Level=Impersonate;',	'\Package.Connections[SSAS_Server].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_0_MDM',	'Data Source=Localhost;Initial Catalog=DWH_0_MDM;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_0_MDM].Properties[ConnectionString]',	'String'
UNION SELECT 	'Talentsoft_SourceFolderPath',	'$(DropboxPath)\Input\Talentsoft\Data',	'\Package.Variables[User::Talentsoft_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Talentsoft_ArchiveFolderPath',	'$(DropboxPath)\Input\Talentsoft\Archive',	'\Package.Variables[User::Talentsoft_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Talentsoft_ErrorFolderPath',	'$(DropboxPath)\Input\Talentsoft\Error',	'\Package.Variables[User::Talentsoft_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_SourceFolderPath',	'$(DropboxPath)\Input\Manual\Data',	'\Package.Variables[User::Manual_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_ArchiveFolderPath',	'$(DropboxPath)\Input\Manual\Archive',	'\Package.Variables[User::Manual_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_ErrorFolderPath',	'$(DropboxPath)\Input\Manual\Error',	'\Package.Variables[User::Manual_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'MoveFileWhenComplete',	'true',	'\Package.Variables[User::MoveFileWhenComplete].Properties[Value]',	'Boolean'
UNION SELECT 	'iLevel_SourceFolderPath',	'$(DropboxPath)\Input\iLevel\Data',	'\Package.Variables[User::iLevel_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'iLevel_ArchiveFolderPath',	'$(DropboxPath)\Input\iLevel\Archive',	'\Package.Variables[User::iLevel_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'iLevel_ErrorFolderPath',	'$(DropboxPath)\Input\iLevel\Error',	'\Package.Variables[User::iLevel_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'iLevel_NoOfPeriods',	'60',	'\Package.Variables[User::iLevel_NoOfPeriods].Properties[Value]',	'String'
UNION SELECT 	'iLevel_ExecFilePath',	'$(DropboxPath)\Input\iLevel\Exec\iLevelIntegration.exe',	'\Package.Variables[User::iLevel_ExecFilePath].Properties[Value]',	'String'





END

IF 'DEV' = '$(Environment)'
BEGIN
PRINT '***** Creating Test Data for UTV Enviroment *****';


/*
SELECT 'UNION SELECT '
	  ,'''' + [ConfigurationFilter]+ ''','
      ,'''' + [ConfiguredValue]+ ''','
      ,'''' + [PackagePath]+ ''','
      ,'''' + [ConfiguredValueType]+ ''''
  FROM [dbo].[SSISConfigurations]
*/



TRUNCATE TABLE dbo.SSISConfigurations

INSERT INTO dbo.SSISConfigurations(ConfigurationFilter, ConfiguredValue, PackagePath, ConfiguredValueType)
SELECT 			'DWH_3_Fact',	'Data Source=Ipo-dw-dev-2;Initial Catalog=DWH_3_Fact;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_3_Fact].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_2_Norm',	'Data Source=Ipo-dw-dev-2;Initial Catalog=DWH_2_Norm;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_2_Norm].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_1_Raw',	'Data Source=Ipo-dw-dev-2;Initial Catalog=DWH_1_Raw;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_1_Raw].Properties[ConnectionString]',	'String'
UNION SELECT	'SSAS_Server',	'Data Source=Ipo-dw-dev-2;PROVIDER=MSOLAP;Impersonation Level=Impersonate;',	'\Package.Connections[SSAS_Server].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_0_MDM',	'Data Source=Ipo-dw-dev-2;Initial Catalog=DWH_0_MDM;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_0_MDM].Properties[ConnectionString]',	'String'
UNION SELECT 	'Manual_SourceFolderPath',	'$(DropboxPath)\Input\Manual\Data',	'\Package.Variables[User::Manual_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_ArchiveFolderPath',	'$(DropboxPath)\Input\Manual\Archive',	'\Package.Variables[User::Manual_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_ErrorFolderPath',	'$(DropboxPath)\Input\Manual\Error',	'\Package.Variables[User::Manual_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'MoveFileWhenComplete',	'true',	'\Package.Variables[User::MoveFileWhenComplete].Properties[Value]',	'Boolean'

END

IF 'UAT' = '$(Environment)'
BEGIN
PRINT '***** Creating Test Data for TEST Enviroment *****';



/*
SELECT 'UNION SELECT '
	  ,'''' + [ConfigurationFilter]+ ''','
      ,'''' + [ConfiguredValue]+ ''','
      ,'''' + [PackagePath]+ ''','
      ,'''' + [ConfiguredValueType]+ ''''
  FROM [dbo].[SSISConfigurations]
*/


TRUNCATE TABLE dbo.SSISConfigurations

INSERT INTO dbo.SSISConfigurations(ConfigurationFilter, ConfiguredValue, PackagePath, ConfiguredValueType)
SELECT 			'DWH_3_Fact',	'Data Source=eqtdwuatsrv01;Initial Catalog=DWH_3_Fact;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_3_Fact].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_2_Norm',	'Data Source=eqtdwuatsrv01;Initial Catalog=DWH_2_Norm;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_2_Norm].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_1_Raw',	'Data Source=eqtdwuatsrv01;Initial Catalog=DWH_1_Raw;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_1_Raw].Properties[ConnectionString]',	'String'
UNION SELECT	'SSAS_Server',	'Data Source=eqtdwuatsrv01;PROVIDER=MSOLAP;Impersonation Level=Impersonate;',	'\Package.Connections[SSAS_Server].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_0_MDM',	'Data Source=eqtdwuatsrv01;Initial Catalog=DWH_0_MDM;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_0_MDM].Properties[ConnectionString]',	'String'
UNION SELECT 	'Talentsoft_SourceFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\UAT\Input\Talentsoft\Data',	'\Package.Variables[User::Talentsoft_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Talentsoft_ArchiveFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\UAT\Input\Talentsoft\Archive',	'\Package.Variables[User::Talentsoft_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Talentsoft_ErrorFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\UAT\Input\Talentsoft\Error',	'\Package.Variables[User::Talentsoft_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_SourceFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\UAT\Input\Manual\Data',	'\Package.Variables[User::Manual_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_ArchiveFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\UAT\Input\Manual\Archive',	'\Package.Variables[User::Manual_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_ErrorFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\UAT\Input\Manual\Error',	'\Package.Variables[User::Manual_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'MoveFileWhenComplete',	'true',	'\Package.Variables[User::MoveFileWhenComplete].Properties[Value]',	'Boolean'
UNION SELECT 	'iLevel_SourceFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\UAT\Input\iLevel\Data',	'\Package.Variables[User::iLevel_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'iLevel_ArchiveFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\UAT\Input\iLevel\Archive',	'\Package.Variables[User::iLevel_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'iLevel_ErrorFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\UAT\Input\iLevel\Error',	'\Package.Variables[User::iLevel_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'iLevel_NoOfPeriods',	'3',	'\Package.Variables[User::iLevel_NoOfPeriods].Properties[Value]',	'String'
UNION SELECT 	'iLevel_ExecFilePath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\UAT\Input\iLevel\Exec\iLevelIntegration.exe',	'\Package.Variables[User::iLevel_ExecFilePath].Properties[Value]',	'String'

END


IF 'PROD' = '$(Environment)'
BEGIN
PRINT '***** Creating Test Data for QA Enviroment *****';

TRUNCATE TABLE dbo.SSISConfigurations

INSERT INTO dbo.SSISConfigurations(ConfigurationFilter, ConfiguredValue, PackagePath, ConfiguredValueType)
SELECT 			'DWH_3_Fact',	'Data Source=eqtdwprdsrv01;Initial Catalog=DWH_3_Fact;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_3_Fact].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_2_Norm',	'Data Source=eqtdwprdsrv01;Initial Catalog=DWH_2_Norm;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_2_Norm].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_1_Raw',	'Data Source=eqtdwprdsrv01;Initial Catalog=DWH_1_Raw;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_1_Raw].Properties[ConnectionString]',	'String'
UNION SELECT	'SSAS_Server',	'Data Source=eqtdwprdsrv02;PROVIDER=MSOLAP;Impersonation Level=Impersonate;',	'\Package.Connections[SSAS_Server].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_0_MDM',	'Data Source=eqtdwprdsrv01;Initial Catalog=DWH_0_MDM;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_0_MDM].Properties[ConnectionString]',	'String'
UNION SELECT 	'Talentsoft_SourceFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\PROD\Input\Talentsoft\Data',	'\Package.Variables[User::Talentsoft_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Talentsoft_ArchiveFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\PROD\Input\Talentsoft\Archive',	'\Package.Variables[User::Talentsoft_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Talentsoft_ErrorFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\PROD\Input\Talentsoft\Error',	'\Package.Variables[User::Talentsoft_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_SourceFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\PROD\Input\Manual\Data',	'\Package.Variables[User::Manual_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_ArchiveFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\PROD\Input\Manual\Archive',	'\Package.Variables[User::Manual_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_ErrorFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\PROD\Input\Manual\Error',	'\Package.Variables[User::Manual_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'MoveFileWhenComplete',	'true',	'\Package.Variables[User::MoveFileWhenComplete].Properties[Value]',	'Boolean'
UNION SELECT 	'iLevel_SourceFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\PROD\Input\iLevel\Data',	'\Package.Variables[User::iLevel_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'iLevel_ArchiveFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\PROD\Input\iLevel\Archive',	'\Package.Variables[User::iLevel_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'iLevel_ErrorFolderPath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\PROD\Input\iLevel\Error',	'\Package.Variables[User::iLevel_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'iLevel_NoOfPeriods',	'3',	'\Package.Variables[User::iLevel_NoOfPeriods].Properties[Value]',	'String'
UNION SELECT 	'iLevel_ExecFilePath',	'E:\Dropbox\Dropbox (EQT AB)\DataWarehouse\PROD\Input\iLevel\Exec\iLevelIntegration.exe',	'\Package.Variables[User::iLevel_ExecFilePath].Properties[Value]',	'String'

END


GO

GO
PRINT N'Update complete.';


GO
