/*
Deployment script for DWH_0_Admin

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "DWH_0_Admin"
:setvar DefaultFilePrefix "DWH_0_Admin"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/


GO

GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
-- Test
/*
IF 'Local' = '$(Environment)'
BEGIN
PRINT '***** Creating Test Data for UTV Enviroment *****';

END
*/


DECLARE @Result INT
SELECT  @Result = CASE HOST_NAME() WHEN 'dwbuildsrv01' THEN 1 WHEN 'STO-BIT-01' THEN 2 WHEN 'STO-DB-04' THEN 3 ELSE -1 END


IF @Result = 1
BEGIN 


/*
SELECT 'UNION SELECT '
	  ,'''' + [ConfigurationFilter]+ ''','
      ,'''' + [ConfiguredValue]+ ''','
      ,'''' + [PackagePath]+ ''','
      ,'''' + [ConfiguredValueType]+ ''''
  FROM [dbo].[SSISConfigurations]


*/



TRUNCATE TABLE dbo.SSISConfigurations

INSERT INTO dbo.SSISConfigurations(ConfigurationFilter, ConfiguredValue, PackagePath, ConfiguredValueType)
SELECT 			'DWH_3_Fact',	'Data Source=localhost;Initial Catalog=DWH_3_Fact;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_3_Fact].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_2_Norm',	'Data Source=localhost;Initial Catalog=DWH_2_Norm;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_2_Norm].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_1_Raw',	'Data Source=localhost;Initial Catalog=DWH_1_Raw;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_1_Raw].Properties[ConnectionString]',	'String'
UNION SELECT	'SSAS_Server',	'Data Source=localhost;PROVIDER=MSOLAP;Impersonation Level=Impersonate;',	'\Package.Connections[SSAS_Server].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_0_MDM',	'Data Source=localhost;Initial Catalog=DWH_0_MDM;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_0_MDM].Properties[ConnectionString]',	'String'
UNION SELECT 	'MoveFileWhenComplete',	'true',	'\Package.Variables[User::MoveFileWhenComplete].Properties[Value]',	'Boolean'

UNION SELECT 	'Agresso_SourceFolderPath',		'C:\DW\Agresso\Data',		'\Package.Variables[User::Agresso_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Agresso_ArchiveFolderPath',	'C:\DW\Agresso\Archive',	'\Package.Variables[User::Agresso_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Agresso_ErrorFolderPath',		'C:\DW\Agresso\Error',	'\Package.Variables[User::Agresso_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Agresso_NoOfPeriods',			'3',	'\Package.Variables[User::Agresso_NoOfPeriods].Properties[Value]',	'String'
UNION SELECT 	'Agresso_LastUpdateDaysOffset',	'',	'\Package.Variables[User::Agresso_LastUpdateDaysOffset].Properties[Value]',	'String'

UNION SELECT 	'Manual_ArchiveFolderPath',	'C:\DW\Manual\Archive',	'\Package.Variables[User::Manual_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_SourceFolderPath',	'C:\DW\Manual\Data',	'\Package.Variables[User::Manual_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_ErrorFolderPath',	'C:\DW\Manual\Error',	'\Package.Variables[User::Manual_ErrorFolderPath].Properties[Value]',	'String'

UNION SELECT 	'Agresso_ExecFilePath',			'C:\API\Agresso\AgressoAPI.exe'								,'\Package.Variables[User::Agresso_ExecFilePath].Properties[Value]',	'String'

UNION SELECT 	'BamsNo',	'Provider=SQLNCLI11;Server=STO-DB-05;Initial Catalog=BAMS2NO;Integrated Security=SSPI;',	'\Package.Connections[BamsNo].Properties[ConnectionString]',	'String'
UNION SELECT 	'BamsSe',	'Provider=SQLNCLI11;Server=STO-DB-05;Initial Catalog=BAMS2SE;Integrated Security=SSPI;',	'\Package.Connections[BamsSe].Properties[ConnectionString]',	'String'
UNION SELECT 	'UCAP',	'Data Source=STO-DB-04;Initial Catalog=DW_UcapPL_Staging;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[UCAP].Properties[ConnectionString]',	'String'
END
IF @Result = 2
BEGIN 


/*
SELECT 'UNION SELECT '
	  ,'''' + [ConfigurationFilter]+ ''','
      ,'''' + [ConfiguredValue]+ ''','
      ,'''' + [PackagePath]+ ''','
      ,'''' + [ConfiguredValueType]+ ''''
  FROM [dbo].[SSISConfigurations]
*/



TRUNCATE TABLE dbo.SSISConfigurations

INSERT INTO dbo.SSISConfigurations(ConfigurationFilter, ConfiguredValue, PackagePath, ConfiguredValueType)
SELECT 			'DWH_3_Fact',	'Data Source=localhost;Initial Catalog=DWH_3_Fact;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_3_Fact].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_2_Norm',	'Data Source=localhost;Initial Catalog=DWH_2_Norm;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_2_Norm].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_1_Raw',	'Data Source=localhost;Initial Catalog=DWH_1_Raw;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_1_Raw].Properties[ConnectionString]',	'String'
UNION SELECT	'SSAS_Server',	'Data Source=localhost;PROVIDER=MSOLAP;Impersonation Level=Impersonate;',	'\Package.Connections[SSAS_Server].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_0_MDM',	'Data Source=localhost;Initial Catalog=DWH_0_MDM;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_0_MDM].Properties[ConnectionString]',	'String'
UNION SELECT 	'MoveFileWhenComplete',	'true',	'\Package.Variables[User::MoveFileWhenComplete].Properties[Value]',	'Boolean'

UNION SELECT 	'Agresso_SourceFolderPath',		'E:\DWH_Landing_Area\NextGen\Agresso\Data',		'\Package.Variables[User::Agresso_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Agresso_ArchiveFolderPath',	'E:\DWH_Landing_Area\NextGen\Agresso\Archive',	'\Package.Variables[User::Agresso_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Agresso_ErrorFolderPath',		'E:\DWH_Landing_Area\NextGen\Agresso\Error',	'\Package.Variables[User::Agresso_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Agresso_NoOfPeriods',			'3',	'\Package.Variables[User::Agresso_NoOfPeriods].Properties[Value]',	'String'
UNION SELECT 	'Agresso_LastUpdateDaysOffset',	'',	'\Package.Variables[User::Agresso_LastUpdateDaysOffset].Properties[Value]',	'String'

UNION SELECT 	'Manual_ArchiveFolderPath',	'E:\DWH_Landing_Area\NextGen\Manual\Archive',	'\Package.Variables[User::Manual_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_SourceFolderPath',	'E:\DWH_Landing_Area\NextGen\Manual\Data',	'\Package.Variables[User::Manual_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_ErrorFolderPath',	'E:\DWH_Landing_Area\NextGen\Manual\Error',	'\Package.Variables[User::Manual_ErrorFolderPath].Properties[Value]',	'String'

UNION SELECT 	'Agresso_ExecFilePath',			'C:\API\Agresso\AgressoAPI.exe'								,'\Package.Variables[User::Agresso_ExecFilePath].Properties[Value]',	'String'


UNION SELECT 	'BamsNo',	'Provider=SQLNCLI11;Server=STO-DB-05;Initial Catalog=BAMS2NO;Integrated Security=SSPI;',	'\Package.Connections[BamsNo].Properties[ConnectionString]',	'String'
UNION SELECT 	'BamsSe',	'Provider=SQLNCLI11;Server=STO-DB-05;Initial Catalog=BAMS2SE;Integrated Security=SSPI;',	'\Package.Connections[BamsSe].Properties[ConnectionString]',	'String'
UNION SELECT 	'UCAP',	'Data Source=STO-DB-04;Initial Catalog=DW_UcapPL_Staging;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[UCAP].Properties[ConnectionString]',	'String'
UNION SELECT 	'MDS',	'Data Source=STO-BIT-01;Initial Catalog=MDS;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[MDS].Properties[ConnectionString]',	'String'
END
IF @Result = 3
BEGIN 


/*
SELECT 'UNION SELECT '
	  ,'''' + [ConfigurationFilter]+ ''','
      ,'''' + [ConfiguredValue]+ ''','
      ,'''' + [PackagePath]+ ''','
      ,'''' + [ConfiguredValueType]+ ''''
  FROM [dbo].[SSISConfigurations]
*/



TRUNCATE TABLE dbo.SSISConfigurations

INSERT INTO dbo.SSISConfigurations(ConfigurationFilter, ConfiguredValue, PackagePath, ConfiguredValueType)
SELECT 			'DWH_3_Fact',	'Data Source=localhost;Initial Catalog=DWH_3_Fact;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_3_Fact].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_2_Norm',	'Data Source=localhost;Initial Catalog=DWH_2_Norm;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_2_Norm].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_1_Raw',	'Data Source=localhost;Initial Catalog=DWH_1_Raw;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_1_Raw].Properties[ConnectionString]',	'String'
UNION SELECT	'SSAS_Server',	'Data Source=localhost;PROVIDER=MSOLAP;Impersonation Level=Impersonate;',	'\Package.Connections[SSAS_Server].Properties[ConnectionString]',	'String'
UNION SELECT 	'MoveFileWhenComplete',	'true',	'\Package.Variables[User::MoveFileWhenComplete].Properties[Value]',	'Boolean'

UNION SELECT 	'Agresso_SourceFolderPath',		'E:\DWH_Landing_Area\NextGen\Agresso\Data',		'\Package.Variables[User::Agresso_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Agresso_ArchiveFolderPath',	'E:\DWH_Landing_Area\NextGen\Agresso\Archive',	'\Package.Variables[User::Agresso_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Agresso_ErrorFolderPath',		'E:\DWH_Landing_Area\NextGen\Agresso\Error',	'\Package.Variables[User::Agresso_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Agresso_NoOfPeriods',			'3',	'\Package.Variables[User::Agresso_NoOfPeriods].Properties[Value]',	'String'
UNION SELECT 	'Agresso_LastUpdateDaysOffset',	'',	'\Package.Variables[User::Agresso_LastUpdateDaysOffset].Properties[Value]',	'String'

UNION SELECT 	'Manual_ArchiveFolderPath',	'E:\DWH_Landing_Area\NextGen\Manual\Archive',	'\Package.Variables[User::Manual_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_SourceFolderPath',	'E:\DWH_Landing_Area\NextGen\Manual\Data',	'\Package.Variables[User::Manual_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_ErrorFolderPath',	'E:\DWH_Landing_Area\NextGen\Manual\Error',	'\Package.Variables[User::Manual_ErrorFolderPath].Properties[Value]',	'String'

UNION SELECT 	'Agresso_ExecFilePath',			'E:\Projects\Common\AgressoAPI\AgressoAPI.exe'								,'\Package.Variables[User::Agresso_ExecFilePath].Properties[Value]',	'String'

UNION SELECT 	'BamsNo',	'Provider=SQLNCLI11;Server=STO-DB-05;Initial Catalog=BAMS2NO;Integrated Security=SSPI;',	'\Package.Connections[BamsNo].Properties[ConnectionString]',	'String'
UNION SELECT 	'BamsSe',	'Provider=SQLNCLI11;Server=STO-DB-05;Initial Catalog=BAMS2SE;Integrated Security=SSPI;',	'\Package.Connections[BamsSe].Properties[ConnectionString]',	'String'
UNION SELECT 	'UCAP',	'Data Source=STO-DB-04;Initial Catalog=DW_UcapPL_Staging;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[UCAP].Properties[ConnectionString]',	'String'
UNION SELECT 	'MDS',	'Data Source=STO-BIT-01;Initial Catalog=MDS;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[MDS].Properties[ConnectionString]',	'String'
END
IF @Result = -1
BEGIN 


/*


SELECT 'UNION SELECT '
	  ,'''' + [ConfigurationFilter]+ ''','
      ,'''' + [ConfiguredValue]+ ''','
      ,'''' + [PackagePath]+ ''','
      ,'''' + [ConfiguredValueType]+ ''''
  FROM [dbo].[SSISConfigurations]
*/



TRUNCATE TABLE dbo.SSISConfigurations

INSERT INTO dbo.SSISConfigurations(ConfigurationFilter, ConfiguredValue, PackagePath, ConfiguredValueType)
SELECT 			'DWH_3_Fact',	'Data Source=localhost;Initial Catalog=DWH_3_Fact;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_3_Fact].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_2_Norm',	'Data Source=localhost;Initial Catalog=DWH_2_Norm;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_2_Norm].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_1_Raw',	'Data Source=localhost;Initial Catalog=DWH_1_Raw;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_1_Raw].Properties[ConnectionString]',	'String'
UNION SELECT	'SSAS_Server',	'Data Source=localhost;PROVIDER=MSOLAP;Impersonation Level=Impersonate;',	'\Package.Connections[SSAS_Server].Properties[ConnectionString]',	'String'
UNION SELECT 	'DWH_0_MDM',	'Data Source=localhost;Initial Catalog=DWH_0_MDM;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[DWH_0_MDM].Properties[ConnectionString]',	'String'
UNION SELECT 	'MoveFileWhenComplete',	'true',	'\Package.Variables[User::MoveFileWhenComplete].Properties[Value]',	'Boolean'

UNION SELECT 	'Agresso_SourceFolderPath',		'C:\DW\Agresso\Data',		'\Package.Variables[User::Agresso_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Agresso_ArchiveFolderPath',	'C:\DW\Agresso\Archive',	'\Package.Variables[User::Agresso_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Agresso_ErrorFolderPath',		'C:\DW\Agresso\Error',	'\Package.Variables[User::Agresso_ErrorFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Agresso_ExecFilePath',			'C:\Source\Repos\Datawarehouse\AgressoAPI\AgressoAPI\bin\Debug\AgressoAPI.exe',	'\Package.Variables[User::Agresso_ExecFilePath].Properties[Value]',	'String'
UNION SELECT 	'Agresso_NoOfPeriods',			'3',	'\Package.Variables[User::Agresso_NoOfPeriods].Properties[Value]',	'String'
UNION SELECT 	'Agresso_LastUpdateDaysOffset',	'',	'\Package.Variables[User::Agresso_LastUpdateDaysOffset].Properties[Value]',	'String'

UNION SELECT 	'Manual_ArchiveFolderPath',	'C:\DW\Manual\Archive',	'\Package.Variables[User::Manual_ArchiveFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_SourceFolderPath',	'C:\DW\Manual\Data',	'\Package.Variables[User::Manual_SourceFolderPath].Properties[Value]',	'String'
UNION SELECT 	'Manual_ErrorFolderPath',	'C:\DW\Manual\Error',	'\Package.Variables[User::Manual_ErrorFolderPath].Properties[Value]',	'String'

UNION SELECT 	'BamsNo',	'Provider=SQLNCLI11;Server=STO-DB-05;Initial Catalog=BAMS2NO;Integrated Security=SSPI;',	'\Package.Connections[BamsNo].Properties[ConnectionString]',	'String'
UNION SELECT 	'BamsSe',	'Provider=SQLNCLI11;Server=STO-DB-05;Initial Catalog=BAMS2SE;Integrated Security=SSPI;',	'\Package.Connections[BamsSe].Properties[ConnectionString]',	'String'
UNION SELECT 	'UCAP',	'Data Source=STO-DB-04;Initial Catalog=DW_UcapPL_Staging;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[UCAP].Properties[ConnectionString]',	'String'
UNION SELECT 	'MDS',	'Data Source=STO-BIT-01;Initial Catalog=MDS;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;',	'\Package.Connections[MDS].Properties[ConnectionString]',	'String'
END

GO

GO
PRINT N'Update complete.';


GO
