/*
Deployment script for DWH_1_Raw

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "DWH_1_Raw"
:setvar DefaultFilePrefix "DWH_1_Raw"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

--TRUNCATE TABLE [Manual_RawTyped].[rt_ReportStructure_01]

GO

GO
/*
The column [Manual_RawTyped].[rt_Package_01].[No] is being dropped, data loss could occur.

The type for column PackageID in table [Manual_RawTyped].[rt_Package_01] is currently  INT NOT NULL but is being changed to  SMALLINT NULL. Data loss could occur.
*/

IF EXISTS (select top 1 1 from [Manual_RawTyped].[rt_Package_01])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Dropping [Manual_RawTyped].[rt_Package_01].[NCIDX_SysFileName_ManualPackage_01]...';


GO
DROP INDEX [NCIDX_SysFileName_ManualPackage_01]
    ON [Manual_RawTyped].[rt_Package_01];


GO
PRINT N'Dropping [Manual_RawTyped].[rt_Package_01].[NCIDX_SysModifiedUTC_ManualPackage_01]...';


GO
DROP INDEX [NCIDX_SysModifiedUTC_ManualPackage_01]
    ON [Manual_RawTyped].[rt_Package_01];


GO
PRINT N'Starting rebuilding table [Manual_RawTyped].[rt_Package_01]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [Manual_RawTyped].[tmp_ms_xx_rt_Package_01] (
    [SysFileName]              NVARCHAR (250) NOT NULL,
    [SysDatetimeInsertedUTC]   DATETIME2 (0)  NOT NULL,
    [SysDatetimeUpdatedUTC]    DATETIME2 (0)  NULL,
    [SysDatetimeDeletedUTC]    DATETIME2 (0)  NULL,
    [SysSrcGenerationDateTime] DATETIME2 (0)  NULL,
    [SysModifiedUTC]           DATETIME2 (0)  NOT NULL,
    [SysExecutionLog_key]      INT            NOT NULL,
    [PackageID]                SMALLINT       NULL,
    [PackageGUID]              VARCHAR (36)   NULL,
    [PackageName]              VARCHAR (49)   NULL,
    [Amount]                   MONEY          NULL
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [Manual_RawTyped].[rt_Package_01])
    BEGIN
        INSERT INTO [Manual_RawTyped].[tmp_ms_xx_rt_Package_01] ([SysFileName], [SysDatetimeInsertedUTC], [SysDatetimeUpdatedUTC], [SysDatetimeDeletedUTC], [SysSrcGenerationDateTime], [SysModifiedUTC], [SysExecutionLog_key], [PackageID], [PackageGUID], [PackageName], [Amount])
        SELECT [SysFileName],
               [SysDatetimeInsertedUTC],
               [SysDatetimeUpdatedUTC],
               [SysDatetimeDeletedUTC],
               [SysSrcGenerationDateTime],
               [SysModifiedUTC],
               [SysExecutionLog_key],
               [PackageID],
               [PackageGUID],
               [PackageName],
               [Amount]
        FROM   [Manual_RawTyped].[rt_Package_01];
    END

DROP TABLE [Manual_RawTyped].[rt_Package_01];

EXECUTE sp_rename N'[Manual_RawTyped].[tmp_ms_xx_rt_Package_01]', N'rt_Package_01';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [Manual_RawTyped].[rt_Package_01].[IX_SysFileName]...';


GO
CREATE NONCLUSTERED INDEX [IX_SysFileName]
    ON [Manual_RawTyped].[rt_Package_01]([SysFileName] ASC);


GO
PRINT N'Altering [Manual_RawTyped].[vrt_Package_01]...';


GO
ALTER VIEW [Manual_RawTyped].[vrt_Package_01]ASSELECT * FROM [Manual_RawTyped].[rt_Package_01]
GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
GO

GO
PRINT N'Update complete.';


GO
