

CREATE VIEW Sales.d_CurrentPeriod
AS
SELECT -1 AS CurrentPeriod_key, CAST('N/A' AS NVARCHAR(50)) AS CurrentPeriod , 'N/A' AS CurrentPeriodMonth 
UNION ALL SELECT 1, 'Past', DATENAME(MONTH, DATEADD(MONTH, -1, GETDATE()))
UNION ALL SELECT 2, 'Current', DATENAME(MONTH, DATEADD(MONTH, 0, GETDATE()))
UNION ALL SELECT 3, 'Next', DATENAME(MONTH, DATEADD(MONTH, 1, GETDATE()))