//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgressoAPI.QueryEngineV200606DotNet1.wsdl {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet", ConfigurationName="QueryEngineV200606DotNet1.wsdl.QueryEngineV200606DotNetSoap")]
    internal interface QueryEngineV200606DotNetSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet/GetTempla" +
            "teProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgressoAPI.QueryEngineV200606DotNet1.wsdl.TemplateProperties GetTemplateProperties(long templateId, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet/GetTempla" +
            "teResultAsDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgressoAPI.QueryEngineV200606DotNet1.wsdl.TemplateResultAsDataSet GetTemplateResultAsDataSet(AgressoAPI.QueryEngineV200606DotNet1.wsdl.InputForTemplateResult input, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet/GetTempla" +
            "teResultOptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgressoAPI.QueryEngineV200606DotNet1.wsdl.TemplateResultOptions GetTemplateResultOptions(AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet/GetTempla" +
            "teResultAsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgressoAPI.QueryEngineV200606DotNet1.wsdl.TemplateResultAsXML GetTemplateResultAsXML(AgressoAPI.QueryEngineV200606DotNet1.wsdl.InputForTemplateResult input, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet/GetSearch" +
            "Criteria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgressoAPI.QueryEngineV200606DotNet1.wsdl.SearchCriteria GetSearchCriteria(long templateId, bool hideUnused, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet/GetFormat" +
            "Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgressoAPI.QueryEngineV200606DotNet1.wsdl.FormatInfo GetFormatInfo(long templateId, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet/GetTempla" +
            "teList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgressoAPI.QueryEngineV200606DotNet1.wsdl.TemplateList GetTemplateList(string formList, string descrList, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet/GetTempla" +
            "teMetaData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AgressoAPI.QueryEngineV200606DotNet1.wsdl.TemplateMetaData GetTemplateMetaData(long templateId, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet/About", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string About();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet")]
    public partial class WSCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string clientField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("Client");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet")]
    public partial class TemplateMetaData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SearchCriteria searchCriteriaField;
        
        private TemplateProperties templatePropertiesField;
        
        private FormatInfo formatInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SearchCriteria SearchCriteria {
            get {
                return this.searchCriteriaField;
            }
            set {
                this.searchCriteriaField = value;
                this.RaisePropertyChanged("SearchCriteria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TemplateProperties TemplateProperties {
            get {
                return this.templatePropertiesField;
            }
            set {
                this.templatePropertiesField = value;
                this.RaisePropertyChanged("TemplateProperties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public FormatInfo FormatInfo {
            get {
                return this.formatInfoField;
            }
            set {
                this.formatInfoField = value;
                this.RaisePropertyChanged("FormatInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet")]
    public partial class SearchCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnCodeField;
        
        private string statusField;
        
        private SearchCriteriaProperties[] searchCriteriaPropertiesListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public SearchCriteriaProperties[] SearchCriteriaPropertiesList {
            get {
                return this.searchCriteriaPropertiesListField;
            }
            set {
                this.searchCriteriaPropertiesListField = value;
                this.RaisePropertyChanged("SearchCriteriaPropertiesList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet")]
    public partial class SearchCriteriaProperties : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string columnNameField;
        
        private string descriptionField;
        
        private string restrictionTypeField;
        
        private string fromValueField;
        
        private string toValueField;
        
        private int dataTypeField;
        
        private int dataLengthField;
        
        private int dataCaseField;
        
        private bool isParameterField;
        
        private bool isVisibleField;
        
        private bool isPromptField;
        
        private string relDateCritField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("ColumnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RestrictionType {
            get {
                return this.restrictionTypeField;
            }
            set {
                this.restrictionTypeField = value;
                this.RaisePropertyChanged("RestrictionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FromValue {
            get {
                return this.fromValueField;
            }
            set {
                this.fromValueField = value;
                this.RaisePropertyChanged("FromValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ToValue {
            get {
                return this.toValueField;
            }
            set {
                this.toValueField = value;
                this.RaisePropertyChanged("ToValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int DataLength {
            get {
                return this.dataLengthField;
            }
            set {
                this.dataLengthField = value;
                this.RaisePropertyChanged("DataLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int DataCase {
            get {
                return this.dataCaseField;
            }
            set {
                this.dataCaseField = value;
                this.RaisePropertyChanged("DataCase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IsParameter {
            get {
                return this.isParameterField;
            }
            set {
                this.isParameterField = value;
                this.RaisePropertyChanged("IsParameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsVisible {
            get {
                return this.isVisibleField;
            }
            set {
                this.isVisibleField = value;
                this.RaisePropertyChanged("IsVisible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool IsPrompt {
            get {
                return this.isPromptField;
            }
            set {
                this.isPromptField = value;
                this.RaisePropertyChanged("IsPrompt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string RelDateCrit {
            get {
                return this.relDateCritField;
            }
            set {
                this.relDateCritField = value;
                this.RaisePropertyChanged("RelDateCrit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet")]
    public partial class TemplateProperties : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aggregateIdField;
        
        private string extraTablesField;
        
        private string extraWhereField;
        
        private string frameField;
        
        private string nameField;
        
        private string table1Field;
        
        private string table2Field;
        
        private string table3Field;
        
        private string versionField;
        
        private string versionMinorField;
        
        private bool aggregatedField;
        
        private bool autoFindField;
        
        private bool isBrowseTableField;
        
        private bool useTable1Field;
        
        private bool useTable2Field;
        
        private bool useTable3Field;
        
        private int dWPeriodField;
        
        private int startLevelField;
        
        private long maxRowsField;
        
        private long templateIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AggregateId {
            get {
                return this.aggregateIdField;
            }
            set {
                this.aggregateIdField = value;
                this.RaisePropertyChanged("AggregateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExtraTables {
            get {
                return this.extraTablesField;
            }
            set {
                this.extraTablesField = value;
                this.RaisePropertyChanged("ExtraTables");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ExtraWhere {
            get {
                return this.extraWhereField;
            }
            set {
                this.extraWhereField = value;
                this.RaisePropertyChanged("ExtraWhere");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Frame {
            get {
                return this.frameField;
            }
            set {
                this.frameField = value;
                this.RaisePropertyChanged("Frame");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Table1 {
            get {
                return this.table1Field;
            }
            set {
                this.table1Field = value;
                this.RaisePropertyChanged("Table1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Table2 {
            get {
                return this.table2Field;
            }
            set {
                this.table2Field = value;
                this.RaisePropertyChanged("Table2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Table3 {
            get {
                return this.table3Field;
            }
            set {
                this.table3Field = value;
                this.RaisePropertyChanged("Table3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string VersionMinor {
            get {
                return this.versionMinorField;
            }
            set {
                this.versionMinorField = value;
                this.RaisePropertyChanged("VersionMinor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool Aggregated {
            get {
                return this.aggregatedField;
            }
            set {
                this.aggregatedField = value;
                this.RaisePropertyChanged("Aggregated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool AutoFind {
            get {
                return this.autoFindField;
            }
            set {
                this.autoFindField = value;
                this.RaisePropertyChanged("AutoFind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool IsBrowseTable {
            get {
                return this.isBrowseTableField;
            }
            set {
                this.isBrowseTableField = value;
                this.RaisePropertyChanged("IsBrowseTable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool UseTable1 {
            get {
                return this.useTable1Field;
            }
            set {
                this.useTable1Field = value;
                this.RaisePropertyChanged("UseTable1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool UseTable2 {
            get {
                return this.useTable2Field;
            }
            set {
                this.useTable2Field = value;
                this.RaisePropertyChanged("UseTable2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool UseTable3 {
            get {
                return this.useTable3Field;
            }
            set {
                this.useTable3Field = value;
                this.RaisePropertyChanged("UseTable3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int DWPeriod {
            get {
                return this.dWPeriodField;
            }
            set {
                this.dWPeriodField = value;
                this.RaisePropertyChanged("DWPeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int StartLevel {
            get {
                return this.startLevelField;
            }
            set {
                this.startLevelField = value;
                this.RaisePropertyChanged("StartLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public long MaxRows {
            get {
                return this.maxRowsField;
            }
            set {
                this.maxRowsField = value;
                this.RaisePropertyChanged("MaxRows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public long TemplateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
                this.RaisePropertyChanged("TemplateId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet")]
    public partial class FormatInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FormatProperties[] formatPropertiesListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public FormatProperties[] FormatPropertiesList {
            get {
                return this.formatPropertiesListField;
            }
            set {
                this.formatPropertiesListField = value;
                this.RaisePropertyChanged("FormatPropertiesList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet")]
    public partial class FormatProperties : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amountDisplayFormatField;
        
        private string attributeIdField;
        
        private string breakColNameField;
        
        private string breakTextField;
        
        private string colorField;
        
        private string columnHeaderTextField;
        
        private string columnNameField;
        
        private string conditionTypeField;
        
        private string fontFamilyField;
        
        private string formulaField;
        
        private string sectionTypeField;
        
        private string sectionFormatIDField;
        
        private string typeField;
        
        private bool breakField;
        
        private bool conditionInUseField;
        
        private bool conditionOnlyBreaksField;
        
        private bool fontBoldField;
        
        private bool fontItalicField;
        
        private bool fontStrikeOutField;
        
        private bool fontUnderlineField;
        
        private bool showField;
        
        private bool showTextField;
        
        private int conditionLevelField;
        
        private int dataCaseField;
        
        private int dataLengthField;
        
        private int dataTypeField;
        
        private int displayLengthField;
        
        private int displayOrderField;
        
        private int sortOrderField;
        
        private int textDisplayLengthField;
        
        private int sequenceNoField;
        
        private double conditionFromField;
        
        private double conditionToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AmountDisplayFormat {
            get {
                return this.amountDisplayFormatField;
            }
            set {
                this.amountDisplayFormatField = value;
                this.RaisePropertyChanged("AmountDisplayFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AttributeId {
            get {
                return this.attributeIdField;
            }
            set {
                this.attributeIdField = value;
                this.RaisePropertyChanged("AttributeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BreakColName {
            get {
                return this.breakColNameField;
            }
            set {
                this.breakColNameField = value;
                this.RaisePropertyChanged("BreakColName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BreakText {
            get {
                return this.breakTextField;
            }
            set {
                this.breakTextField = value;
                this.RaisePropertyChanged("BreakText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("Color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ColumnHeaderText {
            get {
                return this.columnHeaderTextField;
            }
            set {
                this.columnHeaderTextField = value;
                this.RaisePropertyChanged("ColumnHeaderText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("ColumnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ConditionType {
            get {
                return this.conditionTypeField;
            }
            set {
                this.conditionTypeField = value;
                this.RaisePropertyChanged("ConditionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FontFamily {
            get {
                return this.fontFamilyField;
            }
            set {
                this.fontFamilyField = value;
                this.RaisePropertyChanged("FontFamily");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Formula {
            get {
                return this.formulaField;
            }
            set {
                this.formulaField = value;
                this.RaisePropertyChanged("Formula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SectionType {
            get {
                return this.sectionTypeField;
            }
            set {
                this.sectionTypeField = value;
                this.RaisePropertyChanged("SectionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SectionFormatID {
            get {
                return this.sectionFormatIDField;
            }
            set {
                this.sectionFormatIDField = value;
                this.RaisePropertyChanged("SectionFormatID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool Break {
            get {
                return this.breakField;
            }
            set {
                this.breakField = value;
                this.RaisePropertyChanged("Break");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool ConditionInUse {
            get {
                return this.conditionInUseField;
            }
            set {
                this.conditionInUseField = value;
                this.RaisePropertyChanged("ConditionInUse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool ConditionOnlyBreaks {
            get {
                return this.conditionOnlyBreaksField;
            }
            set {
                this.conditionOnlyBreaksField = value;
                this.RaisePropertyChanged("ConditionOnlyBreaks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool FontBold {
            get {
                return this.fontBoldField;
            }
            set {
                this.fontBoldField = value;
                this.RaisePropertyChanged("FontBold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool FontItalic {
            get {
                return this.fontItalicField;
            }
            set {
                this.fontItalicField = value;
                this.RaisePropertyChanged("FontItalic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool FontStrikeOut {
            get {
                return this.fontStrikeOutField;
            }
            set {
                this.fontStrikeOutField = value;
                this.RaisePropertyChanged("FontStrikeOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool FontUnderline {
            get {
                return this.fontUnderlineField;
            }
            set {
                this.fontUnderlineField = value;
                this.RaisePropertyChanged("FontUnderline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool Show {
            get {
                return this.showField;
            }
            set {
                this.showField = value;
                this.RaisePropertyChanged("Show");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool ShowText {
            get {
                return this.showTextField;
            }
            set {
                this.showTextField = value;
                this.RaisePropertyChanged("ShowText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int ConditionLevel {
            get {
                return this.conditionLevelField;
            }
            set {
                this.conditionLevelField = value;
                this.RaisePropertyChanged("ConditionLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int DataCase {
            get {
                return this.dataCaseField;
            }
            set {
                this.dataCaseField = value;
                this.RaisePropertyChanged("DataCase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int DataLength {
            get {
                return this.dataLengthField;
            }
            set {
                this.dataLengthField = value;
                this.RaisePropertyChanged("DataLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int DisplayLength {
            get {
                return this.displayLengthField;
            }
            set {
                this.displayLengthField = value;
                this.RaisePropertyChanged("DisplayLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
                this.RaisePropertyChanged("DisplayOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int SortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
                this.RaisePropertyChanged("SortOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public int TextDisplayLength {
            get {
                return this.textDisplayLengthField;
            }
            set {
                this.textDisplayLengthField = value;
                this.RaisePropertyChanged("TextDisplayLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public int SequenceNo {
            get {
                return this.sequenceNoField;
            }
            set {
                this.sequenceNoField = value;
                this.RaisePropertyChanged("SequenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public double ConditionFrom {
            get {
                return this.conditionFromField;
            }
            set {
                this.conditionFromField = value;
                this.RaisePropertyChanged("ConditionFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public double ConditionTo {
            get {
                return this.conditionToField;
            }
            set {
                this.conditionToField = value;
                this.RaisePropertyChanged("ConditionTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet")]
    public partial class TemplateHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long templateIdField;
        
        private string companyCodeField;
        
        private string frameField;
        
        private string functionIdField;
        
        private string moduleField;
        
        private string nameField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TemplateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
                this.RaisePropertyChanged("TemplateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Frame {
            get {
                return this.frameField;
            }
            set {
                this.frameField = value;
                this.RaisePropertyChanged("Frame");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FunctionId {
            get {
                return this.functionIdField;
            }
            set {
                this.functionIdField = value;
                this.RaisePropertyChanged("FunctionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
                this.RaisePropertyChanged("Module");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet")]
    public partial class TemplateList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TemplateHeader[] templateHeaderListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public TemplateHeader[] TemplateHeaderList {
            get {
                return this.templateHeaderListField;
            }
            set {
                this.templateHeaderListField = value;
                this.RaisePropertyChanged("TemplateHeaderList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet")]
    public partial class TemplateResultAsXML : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnCodeField;
        
        private string statusField;
        
        private string templateResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TemplateResult {
            get {
                return this.templateResultField;
            }
            set {
                this.templateResultField = value;
                this.RaisePropertyChanged("TemplateResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet")]
    public partial class TemplateResultAsDataSet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnCodeField;
        
        private string statusField;
        
        private System.Data.DataSet templateResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Data.DataSet TemplateResult {
            get {
                return this.templateResultField;
            }
            set {
                this.templateResultField = value;
                this.RaisePropertyChanged("TemplateResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet")]
    public partial class TemplateResultOptions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool showDescriptionsField;
        
        private bool aggregatedField;
        
        private bool overrideAggregationField;
        
        private bool calculateFormulasField;
        
        private bool formatAlternativeBreakColumnsField;
        
        private bool removeHiddenColumnsField;
        
        private string filterField;
        
        private long firstRecordField;
        
        private long lastRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ShowDescriptions {
            get {
                return this.showDescriptionsField;
            }
            set {
                this.showDescriptionsField = value;
                this.RaisePropertyChanged("ShowDescriptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Aggregated {
            get {
                return this.aggregatedField;
            }
            set {
                this.aggregatedField = value;
                this.RaisePropertyChanged("Aggregated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool OverrideAggregation {
            get {
                return this.overrideAggregationField;
            }
            set {
                this.overrideAggregationField = value;
                this.RaisePropertyChanged("OverrideAggregation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool CalculateFormulas {
            get {
                return this.calculateFormulasField;
            }
            set {
                this.calculateFormulasField = value;
                this.RaisePropertyChanged("CalculateFormulas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool FormatAlternativeBreakColumns {
            get {
                return this.formatAlternativeBreakColumnsField;
            }
            set {
                this.formatAlternativeBreakColumnsField = value;
                this.RaisePropertyChanged("FormatAlternativeBreakColumns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool RemoveHiddenColumns {
            get {
                return this.removeHiddenColumnsField;
            }
            set {
                this.removeHiddenColumnsField = value;
                this.RaisePropertyChanged("RemoveHiddenColumns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("Filter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long FirstRecord {
            get {
                return this.firstRecordField;
            }
            set {
                this.firstRecordField = value;
                this.RaisePropertyChanged("FirstRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long LastRecord {
            get {
                return this.lastRecordField;
            }
            set {
                this.lastRecordField = value;
                this.RaisePropertyChanged("LastRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.agresso.com/QueryEngineService/QueryEngineV200606DotNet")]
    public partial class InputForTemplateResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long templateIdField;
        
        private TemplateResultOptions templateResultOptionsField;
        
        private SearchCriteriaProperties[] searchCriteriaPropertiesListField;
        
        private string pipelineAssociatedNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TemplateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
                this.RaisePropertyChanged("TemplateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TemplateResultOptions TemplateResultOptions {
            get {
                return this.templateResultOptionsField;
            }
            set {
                this.templateResultOptionsField = value;
                this.RaisePropertyChanged("TemplateResultOptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public SearchCriteriaProperties[] SearchCriteriaPropertiesList {
            get {
                return this.searchCriteriaPropertiesListField;
            }
            set {
                this.searchCriteriaPropertiesListField = value;
                this.RaisePropertyChanged("SearchCriteriaPropertiesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PipelineAssociatedName {
            get {
                return this.pipelineAssociatedNameField;
            }
            set {
                this.pipelineAssociatedNameField = value;
                this.RaisePropertyChanged("PipelineAssociatedName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface QueryEngineV200606DotNetSoapChannel : AgressoAPI.QueryEngineV200606DotNet1.wsdl.QueryEngineV200606DotNetSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class QueryEngineV200606DotNetSoapClient : System.ServiceModel.ClientBase<AgressoAPI.QueryEngineV200606DotNet1.wsdl.QueryEngineV200606DotNetSoap>, AgressoAPI.QueryEngineV200606DotNet1.wsdl.QueryEngineV200606DotNetSoap {
        
        public QueryEngineV200606DotNetSoapClient() {
        }
        
        public QueryEngineV200606DotNetSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryEngineV200606DotNetSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryEngineV200606DotNetSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryEngineV200606DotNetSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AgressoAPI.QueryEngineV200606DotNet1.wsdl.TemplateProperties GetTemplateProperties(long templateId, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials) {
            return base.Channel.GetTemplateProperties(templateId, credentials);
        }
        
        public AgressoAPI.QueryEngineV200606DotNet1.wsdl.TemplateResultAsDataSet GetTemplateResultAsDataSet(AgressoAPI.QueryEngineV200606DotNet1.wsdl.InputForTemplateResult input, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials) {
            return base.Channel.GetTemplateResultAsDataSet(input, credentials);
        }
        
        public AgressoAPI.QueryEngineV200606DotNet1.wsdl.TemplateResultOptions GetTemplateResultOptions(AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials) {
            return base.Channel.GetTemplateResultOptions(credentials);
        }
        
        public AgressoAPI.QueryEngineV200606DotNet1.wsdl.TemplateResultAsXML GetTemplateResultAsXML(AgressoAPI.QueryEngineV200606DotNet1.wsdl.InputForTemplateResult input, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials) {
            return base.Channel.GetTemplateResultAsXML(input, credentials);
        }
        
        public AgressoAPI.QueryEngineV200606DotNet1.wsdl.SearchCriteria GetSearchCriteria(long templateId, bool hideUnused, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials) {
            return base.Channel.GetSearchCriteria(templateId, hideUnused, credentials);
        }
        
        public AgressoAPI.QueryEngineV200606DotNet1.wsdl.FormatInfo GetFormatInfo(long templateId, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials) {
            return base.Channel.GetFormatInfo(templateId, credentials);
        }
        
        public AgressoAPI.QueryEngineV200606DotNet1.wsdl.TemplateList GetTemplateList(string formList, string descrList, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials) {
            return base.Channel.GetTemplateList(formList, descrList, credentials);
        }
        
        public AgressoAPI.QueryEngineV200606DotNet1.wsdl.TemplateMetaData GetTemplateMetaData(long templateId, AgressoAPI.QueryEngineV200606DotNet1.wsdl.WSCredentials credentials) {
            return base.Channel.GetTemplateMetaData(templateId, credentials);
        }
        
        public string About() {
            return base.Channel.About();
        }
    }
}
