CREATE TABLE [Deposit_RawTyped].[rt_SeCreditDeposit_01] (
    [SysFileName]                         NVARCHAR (250)  NOT NULL,
    [SysDatetimeInsertedUTC]              DATETIME2 (0)   NOT NULL,
    [SysDatetimeUpdatedUTC]               DATETIME2 (0)   NULL,
    [SysDatetimeDeletedUTC]               DATETIME2 (0)   NULL,
    [SysSrcGenerationDateTime]            DATETIME2 (0)   NOT NULL,
    [SysModifiedUTC]                      DATETIME2 (0)   NOT NULL,
    [SysExecutionLog_key]                 INT             NOT NULL,
    [AccountNumber]                       INT             NOT NULL,
    [Accountproductcode]                  VARCHAR (50)    NULL,
    [Accountproductname]                  VARCHAR (50)    NULL,
    [Accountopeningdate]                  DATETIME        NULL,
    [Accountfirstdepostitdate]            DATETIME        NULL,
    [Accountclosingdate]                  DATETIME        NULL,
    [Termofproduct]                       SMALLINT        NULL,
    [Interestrate]                        DECIMAL (32, 4) NULL,
    [Interestbonusrate]                   DECIMAL (32, 4) NULL,
    [Dateofpaymentofbonusrate]            DATETIME        NULL,
    [Interestpaymentdate]                 DATETIME        NULL,
    [Nominatedbankaccountforwithdrawals]  NVARCHAR (100)  NULL,
    [Amountondeposit]                     DECIMAL (32, 4) NULL,
    [Accruedbutunpaidinterest]            DECIMAL (32, 4) NULL,
    [Accruedbutunpaidbonus]               DECIMAL (32, 4) NULL,
    [Dateoflastwithdrawal]                DATETIME        NULL,
    [Dateoflastdeposit]                   DATETIME        NULL,
    [DatelasttransferFrom]                DATETIME        NULL,
    [DatelasttransferTo]                  DATETIME        NULL,
    [Numberofaccountholders]              INT             NULL,
    [Manualaccount]                       VARCHAR (10)    NULL,
    [Accountholder1FirstName]             VARCHAR (100)   NULL,
    [Accountholder1LastName]              VARCHAR (100)   NULL,
    [Accountholder1Personnumber]          VARCHAR (100)   NULL,
    [Accountholder1StreetAddress]         VARCHAR (100)   NULL,
    [Accountholder1CityAddress]           VARCHAR (100)   NULL,
    [Accountholder1Email]                 VARCHAR (100)   NULL,
    [Accountholder1Mobilnumber]           VARCHAR (100)   NULL,
    [Accountholder1TelephoneDaytime]      VARCHAR (100)   NULL,
    [Accountholder1TelephoneEvening]      VARCHAR (100)   NULL,
    [Accountholder1FeedbackQuestion1]     VARCHAR (500)   NULL,
    [Accountholder1FeedbackQuestion2]     VARCHAR (500)   NULL,
    [Accountholder1FeedbackQuestion3]     VARCHAR (500)   NULL,
    [Accountholder1FeedbackQuestion4]     VARCHAR (500)   NULL,
    [Accountholder1AMLquestionsQuestion1] VARCHAR (500)   NULL,
    [Accountholder1AMLquestionsQuestion2] VARCHAR (500)   NULL,
    [Accountholder1AMLquestionsQuestion3] VARCHAR (500)   NULL,
    [Accountholder2FirstName]             VARCHAR (100)   NULL,
    [Accountholder2LastName]              VARCHAR (100)   NULL,
    [Accountholder2Personnumber]          VARCHAR (100)   NULL,
    [Accountholder2StreetAddress]         VARCHAR (100)   NULL,
    [Accountholder2CityAddress]           VARCHAR (100)   NULL,
    [Accountholder2Email]                 VARCHAR (100)   NULL,
    [Accountholder2Mobilnumber]           VARCHAR (100)   NULL,
    [Accountholder2TelephoneDaytime]      VARCHAR (100)   NULL,
    [Accountholder2TelephoneEvening]      VARCHAR (100)   NULL,
    [Accountholder2FeedbackQuestion1]     VARCHAR (500)   NULL,
    [Accountholder2FeedbackQuestion2]     VARCHAR (500)   NULL,
    [Accountholder2FeedbackQuestion3]     VARCHAR (500)   NULL,
    [Accountholder2FeedbackQuestion4]     VARCHAR (500)   NULL,
    [Accountholder2AMLquestionsQuestion1] VARCHAR (500)   NULL,
    [Accountholder2AMLquestionsQuestion2] VARCHAR (500)   NULL,
    [Accountholder2AMLquestionsQuestion3] VARCHAR (500)   NULL,
    [Accountholder3FirstName]             VARCHAR (100)   NULL,
    [Accountholder3LastName]              VARCHAR (100)   NULL,
    [Accountholder3Personnumber]          VARCHAR (100)   NULL,
    [Accountholder3StreetAddress]         VARCHAR (100)   NULL,
    [Accountholder3CityAddress]           VARCHAR (100)   NULL,
    [Accountholder3Email]                 VARCHAR (100)   NULL,
    [Accountholder3Mobilnumber]           VARCHAR (100)   NULL,
    [Accountholder3TelephoneDaytime]      VARCHAR (100)   NULL,
    [Accountholder3TelephoneEvening]      VARCHAR (100)   NULL,
    [Accountholder3FeedbackQuestion1]     VARCHAR (500)   NULL,
    [Accountholder3FeedbackQuestion2]     VARCHAR (500)   NULL,
    [Accountholder3FeedbackQuestion3]     VARCHAR (500)   NULL,
    [Accountholder3FeedbackQuestion4]     VARCHAR (500)   NULL,
    [Accountholder3AMLquestionsQuestion1] VARCHAR (500)   NULL,
    [Accountholder3AMLquestionsQuestion2] VARCHAR (500)   NULL,
    [Accountholder3AMLquestionsQuestion3] VARCHAR (500)   NULL,
    [Accountholder4FirstName]             VARCHAR (100)   NULL,
    [Accountholder4LastName]              VARCHAR (100)   NULL,
    [Accountholder4Personnumber]          VARCHAR (100)   NULL,
    [Accountholder4StreetAddress]         VARCHAR (100)   NULL,
    [Accountholder4CityAddress]           VARCHAR (100)   NULL,
    [Accountholder4Email]                 VARCHAR (100)   NULL,
    [Accountholder4Mobilnumber]           VARCHAR (100)   NULL,
    [Accountholder4TelephoneDaytime]      VARCHAR (100)   NULL,
    [Accountholder4TelephoneEvening]      VARCHAR (100)   NULL,
    [Accountholder4FeedbackQuestion1]     VARCHAR (500)   NULL,
    [Accountholder4FeedbackQuestion2]     VARCHAR (500)   NULL,
    [Accountholder4FeedbackQuestion3]     VARCHAR (500)   NULL,
    [Accountholder4FeedbackQuestion4]     VARCHAR (500)   NULL,
    [Accountholder4AMLquestionsQuestion1] VARCHAR (500)   NULL,
    [Accountholder4AMLquestionsQuestion2] VARCHAR (500)   NULL,
    [Accountholder4AMLquestionsQuestion3] VARCHAR (500)   NULL,
    CONSTRAINT [PK_DepositSeCreditDeposit_01] PRIMARY KEY CLUSTERED ([AccountNumber] ASC, [SysSrcGenerationDateTime] DESC)
);




GO
CREATE NONCLUSTERED INDEX [NCIDX_SysModifiedUTC_DepositSeCreditDeposit_01]
    ON [Deposit_RawTyped].[rt_SeCreditDeposit_01]([SysModifiedUTC] ASC);


GO
CREATE NONCLUSTERED INDEX [NCIDX_SysFileName_DepositSeCreditDeposit_01]
    ON [Deposit_RawTyped].[rt_SeCreditDeposit_01]([SysFileName] ASC);

