CREATE TABLE [Sugar_RawTyped].[r_Omrade] (
    [Omrade_key]                       INT            IDENTITY (1, 1) NOT NULL,
    [SysExecutionLog_key]              INT            NOT NULL,
    [SysDatetimeInsertedUTC]           DATETIME2 (0)  NOT NULL,
    [SysDatetimeUpdatedUTC]            DATETIME2 (0)  NULL,
    [SysDatetimeDeletedUTC]            DATETIME2 (0)  NULL,
    [SysModifiedUTC]                   DATETIME2 (0)  NOT NULL,
    [SysIsInferred]                    BIT            NOT NULL,
    [SysValidFromDateTime]             DATETIME2 (0)  NOT NULL,
    [SysSrcGenerationDateTime]         DATETIME2 (0)  NULL,
    [Omrade_bkey]                      NVARCHAR (100) NOT NULL,
    [Name]                             NVARCHAR (255) NULL,
    [Deleted]                          INT            NULL,
    [Byggnationsstatusc]               NVARCHAR (100) NULL,
    [Forsaljningsstatusc]              NVARCHAR (100) NULL,
    [Statusupphandlingc]               NVARCHAR (100) NULL,
    [Iikbeslutc]                       NVARCHAR (100) NULL,
    [Omraderegionc]                    NVARCHAR (100) NULL,
    [Stadsnatddc]                      NVARCHAR (100) NULL,
    [Kommunddc]                        NVARCHAR (100) NULL,
    [Typavortc]                        NVARCHAR (100) NULL,
    [Forsaljningpaborjadc]             DATE           NULL,
    [Efterkampanjpaborjadc]            DATE           NULL,
    [Saljstopputesaljc]                DATE           NULL,
    [Planeradbyggstartc]               DATE           NULL,
    [Planeratklardatumc]               DATE           NULL,
    [Planeradinstallationstartc]       DATE           NULL,
    [Planeratavslutkundinstallc]       DATE           NULL,
    [Dateoverlamnadtillbyggc]          DATE           NULL,
    [Projektnummerifsc]                NVARCHAR (255) NULL,
    [Entreprenorddc]                   NVARCHAR (100) NULL,
    [Ansvarigsaljorganisationc]        NVARCHAR (100) NULL,
    [Ansvarigbyggorganisationc]        NVARCHAR (100) NULL,
    [Useridc]                          NVARCHAR (100) NULL,
    [Userid2c]                         NVARCHAR (100) NULL,
    [Userid3c]                         NVARCHAR (100) NULL,
    [Bidragsomradec]                   NVARCHAR (100) NULL,
    [Natdesignklarc]                   DATE           NULL,
    [Planeratleveransnodlankc]         DATE           NULL,
    [Nodlankdriftsattc]                DATE           NULL,
    [Projekteringddc]                  NVARCHAR (100) NULL,
    [Kommunavtalklarac]                DATE           NULL,
    [Trvbehovsc]                       NVARCHAR (100) NULL,
    [Planeratklardatumtrvc]            DATE           NULL,
    [Antaltrvbehovsc]                  INT            NULL,
    [Antaltrvklarac]                   INT            NULL,
    [Tillstandtrvklarac]               DATE           NULL,
    [Tillstandtrvklaratextc]           NVARCHAR (255) NULL,
    [Allatillstandtrvinskickadec]      DATE           NULL,
    [Antaltrvinskickadec]              INT            NULL,
    [Tillstandlansstyrelsenc]          NVARCHAR (100) NULL,
    [Lansstyrelseninskickatc]          DATE           NULL,
    [Bygglovklarc]                     DATE           NULL,
    [Bygglovklartextc]                 NVARCHAR (255) NULL,
    [Allabygglovinskickadec]           DATE           NULL,
    [Slutdokumentationklarc]           DATE           NULL,
    [Konkurrentc]                      NVARCHAR (255) NULL,
    [Iikgodkantdatumc]                 DATE           NULL,
    [Antalutfordaschaktmeterc]         INT            NULL,
    [Antalplaneradeschaktmeterc]       INT            NULL,
    [Antalfibreradefosarc]             INT            NULL,
    [Planeratantalfosarc]              INT            NULL,
    [Antalmarkavtalbehovsc]            INT            NULL,
    [KkKundkommunikationCountC]        INT            NULL,
    [KrFas1C]                          NVARCHAR (50)  NULL,
    [KrFas2C]                          NVARCHAR (50)  NULL,
    [KrFas3C]                          NVARCHAR (50)  NULL,
    [KrFas4C]                          NVARCHAR (50)  NULL,
    [KrFas5C]                          NVARCHAR (50)  NULL,
    [KrFas6C]                          NVARCHAR (50)  NULL,
    [Ipgeografiipomrade1ipgeografiida] NVARCHAR (100) NULL,
    [UsersIpOmrade1UsersIda]           NVARCHAR (100) NULL,
    CONSTRAINT [PK_Sugar_RawTyped_r_Omrade] PRIMARY KEY CLUSTERED ([Omrade_bkey] ASC, [SysValidFromDateTime] ASC) WITH (DATA_COMPRESSION = PAGE)
);






GO
CREATE NONCLUSTERED INDEX [NCIDX_SysModifiedUTC_Sugar_RawTyped_r_Omrade]
    ON [Sugar_RawTyped].[r_Omrade]([SysModifiedUTC] ASC) WITH (DATA_COMPRESSION = PAGE);

